/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimelineDialog: typeof import('./src/components/ActivityTimelineDialog.vue')['default']
    AgentCard: typeof import('./src/components/AgentCard.vue')['default']
    AgentDetailDrawer: typeof import('./src/components/AgentDetailDrawer.vue')['default']
    BillingConfigDialog: typeof import('./src/components/BillingConfigDialog.vue')['default']
    ChangelogPanel: typeof import('./src/components/ChangelogPanel.vue')['default']
    CommandPaletteDialog: typeof import('./src/components/CommandPaletteDialog.vue')['default']
    CronCenterDialog: typeof import('./src/components/CronCenterDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileManagerDialog: typeof import('./src/components/FileManagerDialog.vue')['default']
    GatewayDoctorDialog: typeof import('./src/components/GatewayDoctorDialog.vue')['default']
    LayoutSettingsDialog: typeof import('./src/components/LayoutSettingsDialog.vue')['default']
    ProjectBoardDialog: typeof import('./src/components/ProjectBoardDialog.vue')['default']
    QuickMsgFab: typeof import('./src/components/QuickMsgFab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsDialog: typeof import('./src/components/SkillsDialog.vue')['default']
    TokenDetailDialog: typeof import('./src/components/TokenDetailDialog.vue')['default']
    VersionDialog: typeof import('./src/components/VersionDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
